import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/ManualHeader';
import LotteryEntrance from '../components/LotteryEntrance';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lottery</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Header/>
      <LotteryEntrance />
    </div>
  );
}
